Pushing script
bhawesh11/ENOL pull request #31
Opened 2020-10-30 18:17 UTC by Priya-kunwar24

Pushing script Create_claim_without_login for both brands and some xpath path and shared test cases changes.

2020-11-02 10:10 UTC, bhawesh11 commented on src/test/java/ApplicationPages/ContactInformationPage.java
> +	//@FindBy(id = "mat-input-7")
unused comment should be removed from code

2020-11-02 10:11 UTC, bhawesh11 commented on src/test/java/ApplicationPages/TellUsMore.java
> +	//@FindBy(xpath="//mat-label[contains(text(),'State')]//ancestor::label")
Remove commented/unused code

2020-11-02 10:12 UTC, bhawesh11 requested changes

2020-11-02 10:12 UTC, bhawesh11 commented on src/test/java/testApparent/TC_Apparent.java
> -	@Test(enabled = true, priority = 5, description = "Simple Claim")
Enable test cases

2020-11-02 12:53 UTC, yogesh25 commented on src/test/java/ApplicationPages/ContactInformationPage.java
> +	//@FindBy(id = "mat-input-7")
resolved

2020-11-02 12:54 UTC, yogesh25 commented on src/test/java/ApplicationPages/ContactInformationPage.java
> +	//@FindBy(id = "mat-input-7")
resolved

2020-11-02 12:54 UTC, yogesh25 commented on src/test/java/ApplicationPages/TellUsMore.java
> +	//@FindBy(xpath="//mat-label[contains(text(),'State')]//ancestor::label")
resolved.

2020-11-02 12:54 UTC, yogesh25 commented on src/test/java/testApparent/TC_Apparent.java
> -	@Test(enabled = true, priority = 5, description = "Simple Claim")
resolved.

2020-11-03 09:05 UTC, bhawesh11 approved these changes

2020-11-03 09:05 UTC, merged